version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Upgrading environment packages...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Executing PyTest quality validation check...
      - pytest test_app.py
  build:
    commands:
      - echo Quality gates passed! Packaging deployment artifacts...

artifacts:
  files:
    - app.py
    - requirements.txt
    - appspec.yml
    - scripts/**/*